### ISSUE TITLE
Supporting GCS as a storage

### ISSUE THREAD

**Issue by ChakshuGautam** [project-sunbird/sunbird-cloud-storage-sdk#34]
I was looking into the repository and found that GCS is currently not supported. There seems to be two way to do this right now.
1. Implementation of GCS using `jclouds`.
2. A proxy in front of GCS which transparently converts it to S3 compatible. I found an [open-source library](https://github.com/gaul/s3proxy) that seems to be doing the same
`[GSC] ---- [S3Proxy] ---- [sunbird-cloud-storage-sdk (assuming this to be S3)]`

@vrayulu @pkranga  do you think 2 is a viable option until 1 is implemented?

**Comment by anandp504** [comment]
@ChakshuGautam The support for GCS is already implemented. The artifact with the changes can be used in your project from the maven central. The version with support for GCS is [1.4.1](https://mvnrepository.com/artifact/org.sunbird/cloud-store-sdk_2.12/1.4.1). The details of the implementation can be found in the [sunbird-cloud-storage-sdk](https://github.com/project-sunbird/sunbird-cloud-storage-sdk/blob/scala-2.12-with-latest/src/main/scala/org/sunbird/cloud/storage/service/GcloudStorageService.scala) repository.

**Comment by ChakshuGautam** [comment]
Got it. I was looking in the master branch. Thanks, @anandp504 for the prompt reply.

**Comment by ChakshuGautam** [comment]
@anandp504 can you share with me the dependencies of this project? I found one where GCS support was not updated
[Knowledge Platform](https://github.com/project-sunbird/knowledge-platform/blob/release-5.1.0/platform-modules/mimetype-manager/src/main/scala/org/sunbird/cloudstore/StorageService.scala)

Just wanted to create a list of where these changes like these have to be done to make sure GCP is supported completely.
